spring.application.name=simulator
server.port=8085

simulator.dicom.directory=/Users/snof/Desktop/Medic-dcm
simulator.imaging-service.ws-url=ws://localhost:8082/ws/dicom
simulator.frame-interval-ms=1000
