spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "os.org.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
ollama:
  base-url: http://localhost:11434
  model: dcarrascosa/medgemma-1.5-4b-it:Q4_K_M

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}